# Generated by Django 5.2.4 on 2025-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio_profile_date_of_birth_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_status',
            field=models.CharField(blank=True, choices=[('not_applied', 'Not Applied'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='not_applied', max_length=20),
        ),
    ]
