# Generated by Django 5.2.4 on 2025-08-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_qr_code',
            field=models.ImageField(blank=True, help_text='Upload your QR code for payments (eSewa, Khalti, Bank QR, etc.)', null=True, upload_to='seller_qr_codes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_payment_info',
            field=models.CharField(blank=True, help_text='Additional info like phone number or account name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank QR'), ('fonepay', 'FonePay'), ('connectips', 'ConnectIPS'), ('other', 'Other')], help_text='Which payment method does this QR code support?', max_length=50),
        ),
    ]
