# Generated by Django 5.2.4 on 2025-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_payment_qr_code_profile_qr_payment_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('bank', 'Bank QR'), ('fonepay', 'FonePay'), ('connectips', 'ConnectIPS'), ('other', 'Other')], help_text='Which payment method does this QR code support?', max_length=50),
        ),
    ]
