# Generated by Django 5.2.4 on 2025-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='color',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('order', 'Order'), ('message', 'Message'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('qr_payment', 'QR Payment'), ('order_status', 'Order Status')], max_length=20),
        ),
    ]
