# Generated by Django 5.2.4 on 2025-08-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='site_url',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
