# Generated by Django 5.2.4 on 2025-08-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
        ('products', '0010_remove_product_enabled_variation_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation_data',
            field=models.TextField(blank=True, help_text='JSON data of selected variations'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products.productvariation'),
        ),
    ]
