# Generated by Django 5.2.4 on 2025-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
        ('products', '0010_remove_product_enabled_variation_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation_data',
            field=models.TextField(blank=True, help_text='JSON data of selected variations at time of purchase'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products.productvariation'),
        ),
    ]
