# Generated by Django 5.2.4 on 2025-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_variation_data_orderitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway_response',
            field=models.TextField(blank=True, help_text='Raw response from payment gateway', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment gateway reference ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Payment Initiated'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
