# Generated by Django 5.2.4 on 2025-08-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_ordered_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_payment_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When QR payment was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_payment_notes',
            field=models.TextField(blank=True, help_text='Additional notes for QR payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment gateway reference ID or QR reference', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Payment Initiated'), ('pending_qr_confirmation', 'Pending QR Confirmation'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
