# Generated by Django 5.2.4 on 2025-08-21 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_admin_approved_product_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('display_value', models.CharField(blank=True, max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.variationtype')),
            ],
            options={
                'ordering': ['sort_order', 'value'],
                'unique_together': {('variation_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
                ('variation_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationoption')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationtype')),
            ],
            options={
                'unique_together': {('product', 'variation_type', 'variation_option')},
            },
        ),
        migrations.CreateModel(
            name='CategoryVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_variations', to='products.category')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationtype')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('category', 'variation_type')},
            },
        ),
    ]
