# Generated by Django 5.2.4 on 2025-08-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variationtype_variationoption_productvariation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_variations/'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_variations/'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_variations/'),
        ),
    ]
