# Generated by Django 5.2.4 on 2025-08-21 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariation_image1_productvariation_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariations', to='products.variationoption'),
        ),
    ]
