# Generated by Django 5.2.4 on 2025-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariation_variation_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enabled_variation_types',
            field=models.ManyToManyField(blank=True, help_text='Select which variation types are available for this product', to='products.variationtype'),
        ),
    ]
