# Generated by Django 5.2.4 on 2025-08-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_enabled_variation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='products.variationoption'),
        ),
    ]
