# Generated by Django 5.2.4 on 2025-08-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productvariation_variation_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='enabled_variation_types',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationoption'),
        ),
    ]
