# Generated by Django 5.2.4 on 2025-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_enabled_variation_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent - Like New'), ('good', 'Good - Minor wear'), ('fair', 'Fair - Noticeable wear'), ('poor', 'Poor - Heavy wear')], help_text='Condition (for thrift/used products)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Is this product on sale?'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.FloatField(blank=True, help_text='Original price before discount', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('new', 'New Product'), ('thrift', 'Thrift/Used Product'), ('refurbished', 'Refurbished')], default='new', help_text='Type of product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='years_used',
            field=models.IntegerField(blank=True, help_text='How many years used (for thrift products)', null=True),
        ),
    ]
